import express from "express";
import cors from "cors";
import { router } from "../../routes";
import { errorHandler } from "../../presentation/middlewares/errorHandler";
import { setupSwagger } from "./swagger";
const app = express();
app.use(cors());
app.use(express.json());
setupSwagger(app);
app.use("/api", router);
app.use(errorHandler);
export { app };
